name: kingofcomfort
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  audioplayers: ^6.1.0
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  clay_containers: ^0.3.4
  cupertino_icons: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^3.1.1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.1.0
  get: ^4.6.6
  getwidget: ^4.0.0
  glass: ^2.0.0+1
  google_fonts: ^6.2.1
  gradient_icon: ^2.0.9
  grouped_list: ^6.0.0
  http: ^1.2.2
  intl: ^0.19.0
  liquid_swipe: ^3.1.0
  lottie: ^3.1.2
  masonry_grid: ^1.0.0
  material_design_icons_flutter: ^5.0.5955
  meta: ^1.15.0
  provider: ^6.1.5
  shared_preferences: ^2.3.2
  sticky_grouped_list: ^3.1.0
  url_launcher: ^6.3.0
  video_player: ^2.9.2
  weather_icons: ^3.0.0
  widget_mask: ^1.0.0+0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: lol
      fonts:
        - asset: fonts/Kdam.ttf
